const HorsesActionsTypes = {
  FETCH_HORSES_BEGIN: 'FETCH_HORSES_BEGIN',
  FETCH_HORSES_SUCCESS: 'FETCH_HORSES_SUCCESS',
  FETCH_HORSES_FAILURE: 'FETCH_HORSES_FAILURE',
  HORSE_UPDATED: 'HORSE_UPDATED',
  HORSE_UPDATED_FAILED: 'HORSE_UPDATED_FAILED',
  HORSE_DELETED: 'HORSE_DELETED',
  ADD_HORSE: 'ADD_HORSE',
  HORSE_ADD_FAILED: 'HORSE_ADD_FAILED',
};

export default HorsesActionsTypes;
